### ISSUE TITLE
Map author email JohnDoe+blabla@domain.com addresses to the same person

### ISSUE THREAD

**Issue by HenrikBengtsson** [metacran/metacranweb#79] opened 2016-01-04 20:32 UTC
Map author email `JohnDoe+blabla@domain.com` addresses to the same person, e.g. author 'Henrik Singmann' is currently appearing as five different authors because of this.

**Comment by gaborcsardi** [comment] 2016-01-04 20:36
Thanks! I think it is a duplicate of #36.

**Closed by gaborcsardi** 2016-01-04 20:36 UTC
